Импортировать NumPy под именем np

In [1]:
import numpy as np

Напечатать версию и конфигурацию

In [6]:
np.version.version

'1.16.2'

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [8]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [10]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [29]:
c = np.full(10, 2.5)
c

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [30]:
d = np.zeros(10)
d[4] = 1
d

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Создать вектор со значениями от 10 до 49

In [18]:
e = np.arange(10, 50, 1)
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Развернуть вектор (первый становится последним)

In [19]:
e[-1::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [23]:
F = lambda i, j: i * 3 + j

In [24]:
np.fromfunction(F, (3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [31]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

Создать массив 3x3x3 со случайными значениями

In [34]:
a = np.empty((3, 3))
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])


Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [60]:
a = np.empty((10, 10))
print(a)
print(np.min(a))
print(np.max(a))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
0.0
1.0


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [39]:
a = np.empty(30)
print(a)
print(np.mean(a))

[6.92572210e-310 4.68698756e-310 6.92572088e-310 6.92570487e-310
 6.92572224e-310 6.92570487e-310 6.92572231e-310 6.92572067e-310
 6.92570486e-310 6.92570487e-310 6.92570487e-310 6.92571684e-310
 6.92570486e-310 6.92572228e-310 6.92570487e-310 6.92570487e-310
 6.92570486e-310 6.92570486e-310 6.92570486e-310 6.92570487e-310
 6.92572232e-310 6.92570487e-310 6.92572229e-310 6.92570487e-310
 6.92572231e-310 6.92572230e-310 6.92570487e-310 6.92572230e-310
 6.92570487e-310 6.92570486e-310]
6.8510876364978e-310


Создать матрицу с 0 внутри, и 1 на границах

In [45]:
a = np.zeros((10, 10))
a[0, ::] = 1
a[-1, ::] = 1
a[::, 0] = 1
a[::, -1] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Выяснить результат следующих выражений
(	0 * np.nan
	np.nan == np.nan
	np.inf > np.nan
	np.nan - np.nan)

In [46]:
0 * np.nan

nan

In [47]:
np.nan == np.nan

False

In [48]:
np.inf > np.nan

False

In [49]:
np.nan - np.nan

nan

Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [51]:
F = lambda i, j: np.abs(i - j)

In [52]:
np.fromfunction(F, (5, 5))

array([[0., 1., 2., 3., 4.],
       [1., 0., 1., 2., 3.],
       [2., 1., 0., 1., 2.],
       [3., 2., 1., 0., 1.],
       [4., 3., 2., 1., 0.]])

Создать 8x8 матрицу и заполнить её в шахматном порядке

In [53]:
F = lambda i, j: (i - j) % 2

In [54]:
np.fromfunction(F, (8, 8))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [55]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [59]:
a = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])