In [2]:
import numpy as np

Перемножить матрицы 5x3 и 3x2

In [3]:
A, B = np.empty((5, 3)), np.empty((3, 2))
np.dot(A, B)

array([[-1.58169123e-291,  0.00000000e+000],
       [-1.58169124e-291,  0.00000000e+000],
       [-1.58169124e-291,  0.00000000e+000],
       [-1.58169015e-291,  0.00000000e+000],
       [-1.58169124e-291,  0.00000000e+000]])

Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [7]:
A = np.random.randint(1, 10, (100))
A[(A > 3)&(A < 8)] *= -1
A

array([-7,  1, -5,  2, -6,  8, -5,  1, -5,  2, -5,  2, -5,  9,  8,  2, -5,
       -7,  1,  9,  3,  2, -4, -4,  3, -5,  2,  1, -7,  8,  3,  8, -6,  3,
        1, -6,  8, -4,  2,  3, -5,  2,  9, -5, -5,  3,  3,  8, -6,  8,  1,
       -6,  2, -5, -4, -7, -7,  3, -7,  1,  8, -6,  9, -4, -6,  1,  9, -6,
       -6, -6,  1, -7,  9,  8, -7,  2,  8, -5,  1,  9,  9, -6,  2, -5,  1,
        1,  2, -7,  2,  2, -5, -4, -7,  8,  1, -6, -5, -5,  9, -4])

Создать 5x5 матрицу со значениями в строках от 0 до 4

In [8]:
A = np.zeros((5, 5))
A += np.arange(5)
A

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

Есть генератор, сделать с его помощью массив

In [21]:
A = np.fromfunction(lambda x: x, (10, ))
A

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [23]:
np.arange(0, 1, 1/12)[1:]

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333,
       0.91666667])

Отсортировать вектор

In [26]:
A = np.arange(0, 1, 1/12)[1:]
np.random.shuffle(A)
print(A)
A.sort()
print(A)

[0.16666667 0.25       0.33333333 0.08333333 0.66666667 0.58333333
 0.75       0.91666667 0.41666667 0.83333333 0.5       ]
[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333 0.91666667]


Проверить, одинаковы ли 2 numpy массива

In [29]:
A, B = np.arange(0, 1, 1/12)[1:], np.arange(0, 1, 1/12)[1:]


print(np.all(A==B))

np.random.shuffle(A)
np.random.shuffle(B)

print(np.all(A==B))

True
False


Сделать массив неизменяемым


In [33]:
B = np.arange(0, 1, 1/12)[1:]

B.flags.writeable = False

B[0] = 1

ValueError: assignment destination is read-only

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [36]:
A = np.random.random((10, 2))
x = np.sqrt(A[:, 0] ** 2 + A[:, 1] ** 2)
y = np.arctan2(A[:, 0], A[:, 1])

x, y

(array([0.86215126, 0.57243042, 0.65049018, 0.95561858, 1.0482578 ,
        0.97119821, 0.58889701, 0.95432468, 0.42111864, 0.5015538 ]),
 array([1.2460224 , 0.17348867, 0.85508767, 1.17142208, 1.03360653,
        0.83091099, 1.1059345 , 1.2536558 , 1.02661902, 1.17918399]))

Заменить максимальный элемент на ноль

In [37]:
A = np.random.random((10, 2))
A[np.argmax(A)] = 0
A

array([[0.73794595, 0.68631567],
       [0.68114566, 0.2253589 ],
       [0.7294783 , 0.60683824],
       [0.71890201, 0.15037779],
       [0.98542533, 0.04085033],
       [0.26940914, 0.57907744],
       [0.22441051, 0.78738298],
       [0.30328486, 0.37658589],
       [0.        , 0.        ],
       [0.40081329, 0.45547526]])

Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [60]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [63]:
X = np.random.randint(1, 10, (10,))
X *= 2
Y = np.random.randint(1, 10, (10,))
Y *= 2
Y += 1
C = 1.0 / np.subtract.outer(X, Y)
C

array([[-1.        , -0.06666667, -0.33333333, -1.        , -0.14285714,
        -1.        , -0.09090909, -0.11111111, -0.33333333, -0.14285714],
       [ 0.11111111, -0.2       ,  0.14285714,  0.11111111,  0.33333333,
         0.11111111, -1.        ,  1.        ,  0.14285714,  0.33333333],
       [ 0.06666667,  1.        ,  0.07692308,  0.06666667,  0.11111111,
         0.06666667,  0.2       ,  0.14285714,  0.07692308,  0.11111111],
       [ 0.11111111, -0.2       ,  0.14285714,  0.11111111,  0.33333333,
         0.11111111, -1.        ,  1.        ,  0.14285714,  0.33333333],
       [ 0.11111111, -0.2       ,  0.14285714,  0.11111111,  0.33333333,
         0.11111111, -1.        ,  1.        ,  0.14285714,  0.33333333],
       [ 0.11111111, -0.2       ,  0.14285714,  0.11111111,  0.33333333,
         0.11111111, -1.        ,  1.        ,  0.14285714,  0.33333333],
       [ 0.14285714, -0.14285714,  0.2       ,  0.14285714,  1.        ,
         0.14285714, -0.33333333, -1.        

Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy


In [66]:
print(np.iinfo(np.int8).min)
print(np.iinfo(np.int8).max)
print(np.iinfo(np.int16).min)
print(np.iinfo(np.int16).max)
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)
print(np.iinfo(np.int64).min)
print(np.iinfo(np.int64).max)

print(np.finfo(np.float16).min)
print(np.finfo(np.float16).max)
print(np.finfo(np.float32).min)
print(np.finfo(np.float32).max)
print(np.finfo(np.float64).min)
print(np.finfo(np.float64).max)
print(np.finfo(np.float128).min)
print(np.finfo(np.float128).max)


-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308
-1.189731495357231765e+4932
1.189731495357231765e+4932


Напечатать все значения в массиве

In [67]:
X = np.random.randint(1, 10, (10,))
print(X)

[8 2 4 5 8 6 6 1 5 9]


Найти ближайшее к заданному значению число в заданном массиве


In [69]:
X = np.random.randint(1, 10, (10,))
print(X)

X[np.argmin(np.abs(X - 5))]

[5 1 9 3 8 4 9 3 1 5]


5

Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)


In [75]:
Z = np.zeros((10,10), [('point', [('x',float, 1),('y',float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
Z

/home/dexfrost89/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


array([[((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
       [((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
       [((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
       [((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
        ((0., 0.), (0., 0., 0.)), ((0

Дан массив (100,2) координат, найти расстояние от каждой точки до каждой


In [97]:
A = np.random.random((100, 2))
res = np.concatenate([np.subtract.outer(A[:, 0], A[:, 0]).reshape(100, 100, 1), np.subtract.outer(A[:, 1], A[:, 1]).reshape(100, 100, 1)], axis=2)
res = res ** 2
res = np.sqrt(np.sum(res, axis=2))
res.shape
res

array([[0.        , 0.33247408, 0.59239214, ..., 0.5364138 , 0.7353719 ,
        0.25138002],
       [0.33247408, 0.        , 0.3855206 , ..., 0.4313493 , 0.84354598,
        0.32299972],
       [0.59239214, 0.3855206 , 0.        , ..., 0.80546143, 1.22571062,
        0.69322111],
       ...,
       [0.5364138 , 0.4313493 , 0.80546143, ..., 0.        , 0.50703749,
        0.29515501],
       [0.7353719 , 0.84354598, 1.22571062, ..., 0.50703749, 0.        ,
        0.53768236],
       [0.25138002, 0.32299972, 0.69322111, ..., 0.29515501, 0.53768236,
        0.        ]])

Преобразовать массив из float в int


In [100]:
A = np.random.random((10))
A = np.array(A, dtype=np.float)
A
A = np.array(A, dtype=np.int)
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан файл:
1,2,3,4,5
6,,,7,8
,,9,10,11
Как прочитать его?

In [103]:
Z = np.genfromtxt("untitled.txt", delimiter=",")
Z

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

Каков эквивалент функции enumerate для numpy массивов?

In [105]:
A = np.random.random((10,10))

for index, value in np.ndenumerate(A):
    print(index, value, end=' ')

(0, 0) 0.4257748135126225 (0, 1) 0.1516569033782441 (0, 2) 0.2898256723139071 (0, 3) 0.06417800099747417 (0, 4) 0.3669863845387419 (0, 5) 0.8445161722900437 (0, 6) 0.44054799024575053 (0, 7) 0.8414058028101968 (0, 8) 0.9181032165662664 (0, 9) 0.4435848805141188 (1, 0) 0.08761969649177415 (1, 1) 0.40738081888310085 (1, 2) 0.09144633905863608 (1, 3) 0.7536865606442185 (1, 4) 0.6219617451212798 (1, 5) 0.7159561988723082 (1, 6) 0.6987108654536728 (1, 7) 0.9555935102340771 (1, 8) 0.9119568504091555 (1, 9) 0.1836904940162396 (2, 0) 0.6330269014355971 (2, 1) 0.23236805814049133 (2, 2) 0.4016499739033207 (2, 3) 0.036616002516594914 (2, 4) 0.3376834566298623 (2, 5) 0.4307557652574281 (2, 6) 0.06953668545560865 (2, 7) 0.424278566890375 (2, 8) 0.537640674273282 (2, 9) 0.7485819155915653 (3, 0) 0.14303579211089545 (3, 1) 0.9724445378037258 (3, 2) 0.5424626044329615 (3, 3) 0.7629157361247677 (3, 4) 0.2656437947895348 (3, 5) 0.03449985771468267 (3, 6) 0.3367232621153554 (3, 7) 0.6036515555959374 (3,

Сформировать 2D массив с распределением Гаусса


In [106]:
A = np.random.normal(0, 1, (10, 10))
A

array([[ 2.5900922 ,  0.49609188,  0.79013541, -0.75837688, -1.04717919,
         0.78221425, -1.29928628,  0.6702089 , -1.5860831 , -0.96436861],
       [-1.65497341,  0.44462462, -1.1342749 , -0.44000594,  0.74292934,
        -0.21613324, -0.00821982,  0.41226073,  0.08588606, -0.39412293],
       [-0.47787049,  0.59973477, -1.82909645,  0.83521513,  0.39311485,
        -0.23876312,  0.13671213,  1.44207932, -0.80779493,  0.27183196],
       [ 1.41624761,  0.07492241, -0.06231435, -1.91203563, -1.64134418,
         0.17582158,  0.40439699, -1.57617682,  0.78043789,  0.79316972],
       [-0.7200777 , -1.27463384,  1.35978091,  0.32798828,  0.46881384,
         0.47744659,  0.03516499,  2.08458979, -0.13359322, -0.23080347],
       [ 1.44533356, -0.14747958, -0.84451137, -0.1843891 , -0.32217325,
         0.02405601, -1.79262686, -1.0355695 ,  2.06607888,  0.99324033],
       [ 0.81864175, -0.78854519, -1.30018002,  1.02048518, -1.15928141,
        -0.29509168, -0.94642158,  0.12009007

Случайно расположить p элементов в 2D массив


In [129]:
P = np.random.randint(1, 5, (10,))
Z = np.zeros((10,10), dtype=np.int)
np.put(Z, np.random.choice(range(10 * 10), len(P), replace=False), P)
Z

array([[0, 0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 3, 2, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Отнять среднее из каждой строки в матрице


In [141]:
A = np.random.random((11, 10))
A -= np.mean(A, axis=1, keepdims=True)
A

array([[ 0.25415632, -0.2565972 ,  0.20879912,  0.23412808, -0.2136237 ,
        -0.25988358,  0.22618905, -0.15591077,  0.07579183, -0.11304915],
       [-0.23608612, -0.21230769,  0.04136418,  0.15989086, -0.1084405 ,
         0.38678751, -0.11415085, -0.30159207,  0.50897033, -0.12443566],
       [-0.24781933, -0.00071482, -0.04620452,  0.3369902 ,  0.15897947,
        -0.20206677, -0.54724139,  0.26651594,  0.22161716,  0.05994407],
       [ 0.28699401, -0.58159365,  0.32445827,  0.04757209,  0.25334283,
         0.05419952, -0.26443639,  0.26008448, -0.57690543,  0.19628428],
       [-0.05135796,  0.03391192,  0.14240425, -0.09408082, -0.16247584,
         0.28513959,  0.05802223,  0.05287583,  0.10197387, -0.36641308],
       [ 0.24025798,  0.17023466, -0.3048462 , -0.10352625, -0.1751225 ,
         0.09542662,  0.2427848 ,  0.39338955, -0.44858513, -0.11001352],
       [-0.34908846, -0.22206568, -0.19296382, -0.23469036,  0.1298472 ,
         0.22251001,  0.40279412, -0.05933429

Отсортировать матрицу по n-ому столбцу


In [143]:
A = np.random.randint(0, 10, (10, 10))
A[np.argsort(A[:, 4])]

array([[3, 3, 9, 7, 0, 0, 7, 4, 7, 2],
       [6, 0, 3, 7, 1, 0, 6, 0, 7, 1],
       [6, 3, 5, 5, 1, 2, 7, 1, 6, 3],
       [9, 6, 2, 4, 1, 6, 5, 0, 6, 4],
       [7, 4, 2, 6, 5, 0, 6, 9, 5, 2],
       [4, 6, 8, 3, 5, 4, 0, 8, 4, 0],
       [9, 1, 2, 2, 6, 3, 0, 1, 4, 8],
       [6, 7, 0, 4, 8, 1, 8, 5, 0, 0],
       [6, 3, 1, 8, 8, 5, 5, 5, 3, 9],
       [8, 3, 7, 2, 9, 8, 7, 0, 9, 4]])

Определить, есть ли в 2D массиве нулевые столбцы


In [150]:
A = np.random.randint(0, 10, (10, 10))

A[:, 1] = 0

np.any((np.all(A==0, axis=0))==True), A

(True, array([[7, 0, 4, 6, 5, 8, 8, 0, 8, 4],
        [6, 0, 0, 5, 1, 7, 8, 7, 0, 8],
        [1, 0, 6, 2, 7, 2, 2, 9, 7, 9],
        [0, 0, 7, 5, 8, 1, 9, 4, 8, 5],
        [1, 0, 1, 3, 8, 6, 9, 1, 8, 0],
        [7, 0, 6, 9, 3, 1, 0, 6, 7, 6],
        [9, 0, 5, 7, 9, 4, 2, 4, 3, 4],
        [7, 0, 6, 6, 8, 3, 1, 3, 6, 6],
        [6, 0, 8, 9, 0, 4, 1, 7, 5, 6],
        [1, 0, 6, 0, 6, 1, 6, 8, 7, 3]]))

Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)


In [154]:
A = np.random.randint(0, 10, (10,))
Z = np.random.randint(0, 10, (11,))
print(A)
A[Z] += 1
A, Z

[0 9 3 0 2 6 9 4 1 5]


(array([ 1, 10,  4,  1,  3,  7,  9,  5,  1,  5]),
 array([1, 5, 4, 0, 7, 3, 1, 2, 1, 4, 5]))

Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов


In [188]:
A = np.random.randint(0, 2, (100, 100, 3))
A = np.array(A, dtype=np.ubyte)
A = A.reshape(10000, 3)
len(np.unique(A, axis=0)), np.unique(A, axis=0)

(8, array([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1]], dtype=uint8))

Дан четырехмерный массив, посчитать сумму по последним двум осям

In [189]:
A = np.random.randint(0, 2, (2, 3, 4, 5))
np.sum(A, axis=(2, 3))

array([[ 8, 11, 10],
       [ 9, 10,  9]])

Найти диагональные элементы произведения матриц


In [196]:
A, B = np.empty((5, 3)), np.empty((3, 5))
np.diag(np.dot(A, B))

array([2.08250376e-309, 2.77667135e-309,             nan,             nan,
       9.36864801e-309])