In [2]:
import numpy as np

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Поменять 2 строки в матрице


In [4]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники


In [5]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 45) ( 1, 74) ( 5, 45) ( 5, 67) ( 6, 54) ( 6, 83) ( 7, 37) ( 7, 79)
 (19, 23) (19, 60) (23, 60) (26, 86) (26, 93) (37, 79) (45, 67) (45, 74)
 (52, 60) (52, 91) (53, 67) (53, 93) (54, 83) (60, 91) (66, 72) (66, 91)
 (67, 93) (72, 91) (78, 81) (78, 84) (81, 84) (86, 93)]


Дан массив C; создать массив A, что np.bincount(A) == C


In [6]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


Посчитать среднее, используя плавающее окно

In [7]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))


In [8]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


Инвертировать булево значение, или поменять знак у числового массива без создания нового


In [11]:
Z = np.random.randint(0,2,100)
print(Z)
np.logical_not(Z, out=Z)
print(Z)

Z = np.random.uniform(-1.0,1.0,100)
print(Z)
np.negative(Z, out=Z)
print(Z)

[1 0 1 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 0 1 0 1 0 1 1 1 0
 0 0 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1]
[0 1 0 0 0 0 1 0 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1
 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 1 1 1
 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0]
[ 0.0751448  -0.10555082 -0.76696352  0.91124653  0.94924143  0.11282158
 -0.28023739 -0.43300233  0.54877281 -0.04550054 -0.49131157  0.10264625
  0.86786367 -0.90413944  0.49030822 -0.43582566  0.53647866 -0.94508025
 -0.32619311  0.02414347  0.67741373 -0.40633324 -0.39123801  0.64724408
 -0.88487308 -0.38554041  0.94820323 -0.22969927 -0.31639652  0.46626459
  0.93207818  0.98784982 -0.25590986  0.53196296  0.59003241 -0.26572967
  0.13817204 -0.24846399 -0.23803482  0.31679693  0.8481428  -0.8268484
  0.28692028  0.17648319 -0.51304108  0.59827017 -0.75092514 -0.26088651
 -0.49620

Посчитать ранг матрицы


In [14]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(Z)
print(rank)

[[0.82167833 0.01242747 0.2497465  0.05521786 0.5708918  0.83636391
  0.34227844 0.65238264 0.73421713 0.43647686]
 [0.85147915 0.70542859 0.68570094 0.8464718  0.17505796 0.91865016
  0.52518529 0.1167728  0.64966391 0.06059427]
 [0.76824932 0.79373829 0.94670211 0.75563468 0.82279122 0.56427375
  0.93363025 0.20693853 0.27423274 0.14883738]
 [0.35583692 0.76778057 0.31190451 0.88947406 0.39220115 0.99333515
  0.25569069 0.60265212 0.82913255 0.04406706]
 [0.17026954 0.39437053 0.32642497 0.24514864 0.0101619  0.27411904
  0.98975747 0.90068211 0.79705335 0.22452751]
 [0.25459635 0.01572743 0.11114517 0.72194757 0.69968637 0.07356183
  0.24963645 0.43269474 0.93210366 0.01617297]
 [0.24910349 0.58310327 0.39553442 0.56917442 0.9082379  0.80548756
  0.45415291 0.82310314 0.57774224 0.92289673]
 [0.02741964 0.33909085 0.73045802 0.93680346 0.19279626 0.88166904
  0.04886608 0.38284409 0.72165099 0.10105041]
 [0.66981774 0.16253986 0.96662165 0.06797479 0.87838735 0.94206861
  0.45955506

Найти наиболее частое значение в массиве


In [15]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


Извлечь все смежные 3x3 блоки из 10x10 матрицы


In [16]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 3 4]
   [1 1 0]
   [1 0 2]]

  [[3 4 3]
   [1 0 1]
   [0 2 1]]

  [[4 3 4]
   [0 1 3]
   [2 1 1]]

  [[3 4 1]
   [1 3 3]
   [1 1 4]]

  [[4 1 2]
   [3 3 0]
   [1 4 0]]

  [[1 2 0]
   [3 0 3]
   [4 0 4]]

  [[2 0 2]
   [0 3 1]
   [0 4 3]]

  [[0 2 0]
   [3 1 1]
   [4 3 3]]]


 [[[1 1 0]
   [1 0 2]
   [1 2 1]]

  [[1 0 1]
   [0 2 1]
   [2 1 0]]

  [[0 1 3]
   [2 1 1]
   [1 0 2]]

  [[1 3 3]
   [1 1 4]
   [0 2 2]]

  [[3 3 0]
   [1 4 0]
   [2 2 1]]

  [[3 0 3]
   [4 0 4]
   [2 1 0]]

  [[0 3 1]
   [0 4 3]
   [1 0 4]]

  [[3 1 1]
   [4 3 3]
   [0 4 4]]]


 [[[1 0 2]
   [1 2 1]
   [1 2 2]]

  [[0 2 1]
   [2 1 0]
   [2 2 2]]

  [[2 1 1]
   [1 0 2]
   [2 2 1]]

  [[1 1 4]
   [0 2 2]
   [2 1 1]]

  [[1 4 0]
   [2 2 1]
   [1 1 0]]

  [[4 0 4]
   [2 1 0]
   [1 0 2]]

  [[0 4 3]
   [1 0 4]
   [0 2 3]]

  [[4 3 3]
   [0 4 4]
   [2 3 2]]]


 [[[1 2 1]
   [1 2 2]
   [4 4 2]]

  [[2 1 0]
   [2 2 2]
   [4 2 2]]

  [[1 0 2]
   [2 2 1]
   [2 2 2]]

  [[0 2 2]
   [2 1 1]
   [2 2 1]]

  [[2 2 1]
   

Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))


In [18]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


Дан массив 16x16, посчитать сумму по блокам 4x4


In [20]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


Найти n наибольших значений в массиве


In [21]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


Построить прямое произведение массивов (все комбинации с каждым элементом)


In [22]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B


In [23]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[2 5 6]


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])


In [24]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 0 2]
 [0 2 2]
 [4 3 2]
 [4 2 0]
 [3 4 1]
 [0 2 3]
 [2 3 3]
 [2 2 2]
 [2 1 2]
 [1 2 3]]
[[1 0 2]
 [0 2 2]
 [4 3 2]
 [4 2 0]
 [3 4 1]
 [0 2 3]
 [2 3 3]
 [2 1 2]
 [1 2 3]]


Преобразовать вектор чисел в матрицу бинарных представлений


In [25]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Дан двумерный массив. Найти все различные строки


In [26]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [1 0 1]
 [1 1 0]]


Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [31]:
A, B = [0, 0, 1, 1, 0], [1, 0, 1, 0, 0]

print(np.einsum('i->', A))       # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j', A, B))    # np.outer(A, B)

2
[0 0 1 0 0]
1
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 1 0 0]
 [1 0 1 0 0]
 [0 0 0 0 0]]
