Импортировать модули sys numpy pandas

In [1]:
import sys
import numpy as np
import pandas as pd

Создать объект pandas Series из листа, объекта NumPy, и словаря


In [2]:
print(pd.Series([1, 2, 3, 4]))
print(pd.Series(np.arange(5)))
print(pd.Series({'a':1, 'b':3}))

0    1
1    2
2    3
3    4
dtype: int64
0    0
1    1
2    2
3    3
4    4
dtype: int64
a    1
b    3
dtype: int64


Преобразовать объект Seris в DataFrame
создать объект Series
преобразовать в DataFrame


In [3]:
print(pd.Series([1,2 , 3, 4]).to_frame())

   0
0  1
1  2
2  3
3  4



объединить несколько объектов Series в Dataframe

In [4]:
A = pd.Series([1,2 , 3, 4])
B = pd.Series(np.arange(4))

df = pd.concat([A, B], axis=1)
print(df)


   0  1
0  1  0
1  2  1
2  3  2
3  4  3


Присвоить имя индексу объекта Series


In [5]:
A.name = 'new_name'
A

0    1
1    2
2    3
3    4
Name: new_name, dtype: int64

Получить элементы объекта Series A, которых нет в объекте Series B
возвратить вместе с индексами
возвратить значения


In [6]:
A = pd.Series([1, 3, 4, 2, 5])
B = pd.Series([4, 5, 6, 7, 8])
A[~A.isin(B)]

0    1
1    3
3    2
dtype: int64

Получить не пересекающиеся элементы в двух объектах Series
возвратить вместе с индексами
получить объединенный Series без повтороений
получить пересекающиеся данные
отобрать все данные, кроме пересекающихся
возвратить значения

In [7]:
C = pd.Series(np.union1d(A, B))
C

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [8]:
C[~C.isin(np.intersect1d(A, B))]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

Получить от объекта Series показатели описательной статистики


In [12]:
A.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

Узнать частоту уникальных элементов объекта Series (гистограмма)


In [14]:
A.value_counts()

5    1
4    1
3    1
2    1
1    1
dtype: int64

Заменить все элементы объекта Series на "Other", кроме двух наиболее часто встречающихся


In [17]:
A = [1, 1, 2, 2, 3, 4, 5, 6]
A = pd.Series(A)

A[~A.isin(A.value_counts().index[:2])] = 'Other'

A

0        1
1        1
2        2
3        2
4    Other
5    Other
6    Other
7    Other
dtype: object

Создать объект Series в индексах дата каждый день 2019 года, в значениях случайное значение


In [24]:
A = pd.date_range(start='2019-01-01', end='2019-12-31') 
A = pd.Series(np.random.rand(len(A)), index=A)
A

2019-01-01    0.421831
2019-01-02    0.976130
2019-01-03    0.303530
2019-01-04    0.557459
2019-01-05    0.850335
                ...   
2019-12-27    0.282871
2019-12-28    0.236053
2019-12-29    0.761686
2019-12-30    0.833922
2019-12-31    0.623987
Freq: D, Length: 365, dtype: float64

Найти сумму всех вторников


In [26]:
A[A.index.weekday == 2].sum()

29.58273014170827

Для каждого месяца найти среднее значение


In [27]:
A.resample('M').mean()

2019-01-31    0.540910
2019-02-28    0.465093
2019-03-31    0.464960
2019-04-30    0.509417
2019-05-31    0.482855
2019-06-30    0.531453
2019-07-31    0.498487
2019-08-31    0.586539
2019-09-30    0.540835
2019-10-31    0.527843
2019-11-30    0.456189
2019-12-31    0.532814
Freq: M, dtype: float64

Преобразовать объект Series в DataFrame заданной формы (shape)


In [33]:
pd.DataFrame(A.values.reshape((5, 73)))

0         1         2         3         4         5         6   \
0  0.421831  0.976130  0.303530  0.557459  0.850335  0.928349  0.796432   
1  0.466368  0.901639  0.072743  0.226323  0.996035  0.553354  0.102386   
2  0.419426  0.883409  0.985532  0.949005  0.242510  0.410716  0.957354   
3  0.921033  0.690138  0.848491  0.646484  0.731115  0.998381  0.789292   
4  0.576655  0.132316  0.509936  0.342881  0.181825  0.386487  0.704834   

         7         8         9   ...        63        64        65        66  \
0  0.036259  0.804328  0.347132  ...  0.736514  0.187069  0.531201  0.095713   
1  0.809940  0.121166  0.525921  ...  0.975626  0.556325  0.070276  0.217575   
2  0.802375  0.834068  0.642173  ...  0.600650  0.002078  0.090613  0.459910   
3  0.433437  0.421497  0.990646  ...  0.744257  0.439565  0.155140  0.492528   
4  0.804151  0.040727  0.638341  ...  0.650359  0.328591  0.963346  0.143338   

         67        68        69        70        71        72  
0  0.116770  0.027802  0.870629  0.278620  0.479285  0.356670  
1  0.388836  0.022362  0.373930  0.242622  0.154840  0.788727  
2  0.656526  0.581155  0.121397  0.669729  0.264389  0.236185  
3  0.783439  0.841652  0.840131  0.625494  0.929908  0.781729  
4  0.186601  0.282871  0.236053  0.761686  0.833922  0.623987  

[5 rows x 73 columns]

Найти индексы объекта Series кратные 3


In [36]:
A = pd.Series(list(range(100)))

A[A % 3 == 0].index

Int64Index([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
            51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96,
            99],
           dtype='int64')

Получить данные по индексам объекта Series


In [38]:
A[[5, 2, 3]]

5    5
2    2
3    3
dtype: int64

Объединить два объекта Series вертикально и горизонтально


In [42]:
print(pd.concat([pd.Series([1, 2, 3, 4]), pd.Series(list('abcd'))], axis=1))
print(pd.concat([pd.Series([1, 2, 3, 4]), pd.Series(list('abcd'))], axis=0))

   0  1
0  1  a
1  2  b
2  3  c
3  4  d
0    1
1    2
2    3
3    4
0    a
1    b
2    c
3    d
dtype: object


Получить индексы объекта Series A, данные которых содержатся в объетке Series B


In [44]:
A = pd.Series([ 3, 4, 5, 6, 7 ])
B = pd.Series([ 4, 7, 6 ])
print(A[A.isin(B)].index)

Int64Index([1, 3, 4], dtype='int64')


Получить объект Series B, котоырй содержит элементы без повторений объекта A


In [46]:
A = pd.Series([1, 1, 2, 3, 3, 4, 5, 6])
B = A.unique()
B

array([1, 2, 3, 4, 5, 6])

Преобразовать каждый символ объекта Series в верхний регистр


In [49]:
A = pd.Series(['a','bc','d','ef'])
pd.Series([x.upper() for x in A])

0     A
1    BC
2     D
3    EF
dtype: object

преобразовать данных Series в строку


In [54]:
A = pd.Series([1, 2, 3, 4,5,6, 11])
B = pd.Series([str(x) for x in A])
B

0     1
1     2
2     3
3     4
4     5
5     6
6    11
dtype: object

Рассчитать количество символов в объекте Series
преобразовать в строковый тип


In [55]:
[len(x) for x in B]

[1, 1, 1, 1, 1, 1, 2]

Найти разность между объектом Series и смещением объекта Series на n


In [58]:
A = pd.Series([1, 2, 3, 4, 5])

A.diff(periods=1)

0    NaN
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

Преобразовать разыне форматы строк объекта Series в дату


In [60]:
A = pd.Series(['01.01.2019', '02/02/2018', '1 jan 2017'])
pd.to_datetime(A)

0   2019-01-01
1   2018-02-02
2   2017-01-01
dtype: datetime64[ns]

Поскольку работа с датой часто встречается в работе, то см. еще один пример
все данные должны иметь одинаковый формат (часто бывает выгрузка из SQL)
преобразовать в дату
Получить год, месяц, день, день недели, номер дня в году от объекта Series (string)
распарсить в дату и время
получить года
получить месяца
получить дни
получить номер недели
получить номер дня в году


In [62]:
from dateutil.parser import parse
 
A = pd.Series([ '01 nov 2019',
                '2016/03/07',
                '01-01-2011',
                '20120303',
                '2029-11-30'])
 
B = A.map(lambda x: parse(x, yearfirst=True))
print(B.dt.year)
print(B.dt.month)
print(B.dt.day)
print(B.dt.weekofyear)
print(B.dt.dayofyear)

0    2019
1    2016
2    2011
3    2012
4    2029
dtype: int64
0    11
1     3
2     1
3     3
4    11
dtype: int64
0     1
1     7
2     1
3     3
4    30
dtype: int64
0    44
1    10
2    52
3     9
4    48
dtype: int64
0    305
1     67
2      1
3     63
4    334
dtype: int64


Отобрать элементы объекта Series, кторые содержат не менее двух гласных


In [65]:
F = lambda s: s.lower().count('a') + s.lower().count('e') + s.lower().count('o') + s.lower().count('u') + s.lower().count('i')

A = pd.Series(['ab', 'aba', 'abac', 'abacaba'])

for i in A:
    if F(i) >= 2:
        print(i)

aba
abac
abacaba


Отобрать e-маилы из объекта Series (можно юзать регулярки)


In [68]:
import re
 
emails = pd.Series([ 'test text @test.com',
                     'test@google.c',
                     'test.su',
                     'test@pp' ])

mask = emails.map(lambda x: bool(re.match('[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]', x)))
print(emails[mask])

1    test@google.c
dtype: object


Получить среднее значение каждого уникального объекта Series s1 через "маску" другого объекта Series s2

In [78]:
A = pd.Series(np.random.choice(['dog', 'cat', 'horse', 'bird'], 10))
B = pd.Series(np.linspace(1,10,10))
res = B.groupby(A).mean()
print(A)
print(B)
print(res)

0    horse
1    horse
2      dog
3     bird
4      dog
5    horse
6    horse
7    horse
8     bird
9     bird
dtype: object
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64
bird     7.666667
dog      4.000000
horse    4.800000
dtype: float64


 Найти евклидово расстоняие между двумя объектами Series


In [80]:
A = pd.Series(np.random.randint(0, 10, 3))
B = pd.Series(np.random.randint(0, 10, 3))


print(A)
print(B)
np.linalg.norm(B - A)

0    6
1    6
2    7
dtype: int64
0    5
1    0
2    0
dtype: int64


9.273618495495704

 Найти индексы локальных максимумов в объекте Series


In [85]:
A = pd.Series([ 1, 5, 7, 11, 8, 4, 12, 5, 8, 16, 8 ])
d1 = np.sign(np.diff(A))
print(d1)
d2 = np.diff(d1)
print(d2)
print(np.where(d2 == -2)[0] + 1)

[ 1  1  1 -1 -1  1 -1  1  1 -1]
[ 0  0 -2  0  2 -2  2  0 -2]
[3 6 9]


 Заменить пробелы наименее часто встречающимся символов


In [93]:
A = pd.Series(list("Abasoefmnoa cak mlkac,s clkm cka cakscl;las;c "))
print("Abasoefmnoa cak mlkac,s clkm cka cakscl;las;c ".replace(' ', A.value_counts().index[-1]))

Abasoefmnoancaknmlkac,snclkmnckancakscl;las;cn


 Создать объект Series, который содержит в индексах даты выходных дней субботы, а в значениях случайные числа от 1 до 10


In [99]:
s = pd.Series(np.random.randint(0, 10, len(pd.date_range(start='2019-01-01', end='2019-12-31', freq='W-SAT'))),
              pd.date_range(start='2019-01-01', end='2019-12-31',
                            freq='W-SAT'))
print(s)

2019-01-05    9
2019-01-12    1
2019-01-19    3
2019-01-26    6
2019-02-02    0
2019-02-09    4
2019-02-16    8
2019-02-23    6
2019-03-02    4
2019-03-09    8
2019-03-16    2
2019-03-23    6
2019-03-30    0
2019-04-06    3
2019-04-13    2
2019-04-20    2
2019-04-27    4
2019-05-04    1
2019-05-11    1
2019-05-18    5
2019-05-25    4
2019-06-01    7
2019-06-08    1
2019-06-15    3
2019-06-22    3
2019-06-29    2
2019-07-06    7
2019-07-13    1
2019-07-20    1
2019-07-27    3
2019-08-03    1
2019-08-10    5
2019-08-17    3
2019-08-24    3
2019-08-31    7
2019-09-07    4
2019-09-14    3
2019-09-21    7
2019-09-28    3
2019-10-05    7
2019-10-12    0
2019-10-19    7
2019-10-26    4
2019-11-02    8
2019-11-09    5
2019-11-16    9
2019-11-23    7
2019-11-30    7
2019-12-07    3
2019-12-14    0
2019-12-21    0
2019-12-28    7
Freq: W-SAT, dtype: int64


 Заполнить пропущенные даты, значением выше (заполненной даты)


In [103]:
s = pd.Series([ 2, 5, 8 ],
              index=pd.to_datetime([ '2018-01-01',
                                     '2018-01-03',
                                     '2018-01-06' ]))
print(s.resample('D').ffill())

2018-01-01    2
2018-01-02    2
2018-01-03    5
2018-01-04    5
2018-01-05    5
2018-01-06    8
Freq: D, dtype: int64


 Вычислить автокорреляцию объекта Series

In [76]:
s = pd.Series(np.random.randint(0, 10, 10))
print(s.autocorr())

-0.02941176470588235


In [15]:
import sys
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

# Прочитать файл CSV (определенные столбцы и определенное кол-во строк) и перевести его в DataFrame
 
df = pd.read_csv('https://raw.githubusercontent.com/Grossmend/CSV/master/titanic/data.csv', nrows=10, usecols=['Name', 'Sex', 'Survived'])
print(df)
# Прочитать файл CSV и перевести каждую 100-ую строку в DataFrame
 
df = pd.read_csv('https://raw.githubusercontent.com/Grossmend/CSV/master/titanic/data.csv', chunksize=100)
df_each = pd.DataFrame()
for chunk in df:
    df_each = df_each.append(chunk.iloc[0,:])
print(df_each)
# 36. Преобразовать индексы объекта Series в столбец DataFrame
 
test_list = 'abcedf'
test_arr = np.arange(len(test_list))
test_dict = dict(zip(test_list, test_arr))
s = pd.Series(test_dict)
 
df = s.to_frame().reset_index()
df.columns=['letter', 'number']
print(df)
# Посмотреть информацию объекта DataFrame
 
df = pd.read_csv('https://raw.githubusercontent.com/Grossmend/CSV/master/titanic/data.csv', nrows=10)
 
# Вывести формат каждого столбца
print(df.dtypes)
 
# Вывести размерность DataFrame
print(df.shape)
 
# Вывести общую статистику
print(df.describe())

   Survived                                               Name     Sex
0         0                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         1                             Heikkinen, Miss. Laina  female
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4         0                           Allen, Mr. William Henry    male
5         0                                   Moran, Mr. James    male
6         0                            McCarthy, Mr. Timothy J    male
7         0                     Palsson, Master. Gosta Leonard    male
8         1  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9         1                Nasser, Mrs. Nicholas (Adele Achem)  female
      Age    Cabin Embarked      Fare  \
0    22.0      NaN        S    7.2500   
100  28.0      NaN        S    7.8958   
200  28.0      NaN        S    9.5000   
300   NaN      NaN        Q    7.7500   
400  39.0     