# базовые операции над массивами


Математические операции над массивами выполняются поэлементно. Создается новый массив, который заполняется результатами действия оператора.

In [4]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a + b
a - b
a * b
a / b  # При делении на 0 возвращается inf (бесконечность)
a ** b
#a % b  # При взятии остатка от деления на 0 возвращается

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:7: RuntimeWarning: divide by zero encountered in true_divide


array([     1,     30,   1600, 125000])

Для этого, естественно, массивы должны быть одинаковых размеров.

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 2], [3, 4], [5, 6]])
c + d

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Также можно производить математические операции между массивом и числом. В этом случае к каждому элементу прибавляется (или что вы там делаете) это число.

In [6]:
a + 1
a ** 3
a < 35  # И фильтрацию можно проводить

array([ True,  True, False, False])

NumPy также предоставляет множество математических операций для обработки массивов:

In [7]:
np.cos(a)
np.arctan(a)
np.sinh(a)

array([2.42582598e+08, 5.34323729e+12, 1.17692633e+17, 2.59235276e+21])

more: https://docs.scipy.org/doc/numpy/reference/routines.math.html

По умолчанию, эти операции применяются к массиву, как если бы он был списком чисел, независимо от его формы. Однако, указав параметр axis, можно применить операцию для указанной оси массива:

In [8]:
a.min(axis=0)  # Наименьшее число в каждом столбце
a.min(axis=1)  # Наименьшее число в каждой строке

AxisError: axis 1 is out of bounds for array of dimension 1